apiVersion: 1

datasources:
  - name: DevLake MySQL
    type: mysql
    access: proxy
    url: localhost:3307
    database: lake
    user: merico
    secureJsonData:
      password: merico
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timezone: UTC
    isDefault: true
    editable: true